---
- name: Import Windows-specific configuration
  ansible.builtin.include_tasks: noauto_configure_Windows.yml
  when: ansible_os_family == "Windows"

- name: Import Unix-specific configuration
  ansible.builtin.include_tasks: noauto_configure_Unix.yml
  when: ansible_os_family != "Windows"
