---
- name: Import Windows-specific service management
  ansible.builtin.include_tasks: noauto_service_Windows.yml
  when: ansible_os_family == "Windows"

- name: Import Unix-specific service management
  ansible.builtin.include_tasks: noauto_service_Unix.yml
  when: ansible_os_family != "Windows"
