---
- name: Check existing SSH firewall rule
  ansible.windows.win_shell: |
    $port = {{ openssh_server.port }}
    $ruleName = "OpenSSH-Server-In-TCP"
    $rule = Get-NetFirewallRule -Name $ruleName -ErrorAction SilentlyContinue
    if ($rule) {
      $portFilter = $rule | Get-NetFirewallPortFilter
      if ($portFilter.LocalPort -eq $port -and $rule.Profile -match 'Any') {
        Write-Output "ok"
      } else {
        Write-Output "update"
      }
    } else {
      Write-Output "create"
    }
  register: openssh_firewall_rule_state
  changed_when: false
  become: true
  become_method: ansible.builtin.runas
  become_user: "{{ ansible_user }}"

- name: Ensure SSH port is open in Windows Firewall
  ansible.windows.win_shell: |
    $port = {{ openssh_server.port }}
    $defaultName = "OpenSSH-Server-In-TCP"
    $defaultDisplayName = "OpenSSH SSH Server (sshd)"
    $defaultRule = Get-NetFirewallRule -Name "$defaultName" -ErrorAction SilentlyContinue
    if ($defaultRule) {
      $defaultRule | Set-NetFirewallRule `
        -LocalPort $port `
        -Profile Any
    } else {
      New-NetFirewallRule -Name $defaultName `
        -DisplayName "$defaultDisplayName" `
        -Enabled True `
        -Direction Inbound `
        -Protocol TCP `
        -Action Allow `
        -LocalPort $port `
        -Profile Any
    }
  when: openssh_firewall_rule_state.stdout | trim != 'ok'
  become: true
  become_method: ansible.builtin.runas
  become_user: "{{ ansible_user }}"
