---
- name: Converge
  hosts: all

  vars_files:
    - ../../vars/molecule_vars.yml

  pre_tasks:
    - name: Merge openssh_server overrides with defaults (Unix only)
      ansible.builtin.set_fact:
        openssh_server: "{{ openssh_server | default({}) | combine(openssh_server_molecule_overrides | default({}), recursive=true) }}"
      when:
        - openssh_server_molecule_overrides is defined

  roles:
    - role: pluggero.openssh
